language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  


before_script:
  - cp .env.travis .env
  - mysql -e 'create database CDJ_BD;'
  - composer self-update
  - composer install --no-interaction
  
script:
  - php artisan migrate --seed
  - vendor/bin/phpunit
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
- php vendor/bin/coveralls -v

#sudo: false
#
#env:
#  global:
#    - setup=basic
#    
#matrix:
#  include:
#    - php: 5.5
#      env: setup=lowest
#  - php: 5.6
#     env: setup=stable
#
#
#
#services:
#  - redis-server
#  - mysql
#
#before_install:
#  - travis_retry composer self-update
#
#install:
# - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
#  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
#  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi
#
#before_script:
#  - mysql -e 'create database CDJ_BD;'
#
#script:
#  - php artisan migrate --seed
#  - vendor/bin/phpunit
